pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x
    node_12_x:
      node_version: 12.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: Install Node.js

- task: Npm@1
  inputs:
    command: install
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: custom
    customCommand: 'run test'
  displayName: 'npm run test'
